# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a91ed8ac45b0c5daf398ea3d5f9783d5d508ba240bb6b8225ba601e8f6fd2e1fab46370adfdc2e6e17c237e8690b6da1268d4db99e54ff0c082f9c935de0f46

test:
  secret_key_base: 57895be2eeb07efebd8d0d2866cea1e55278f9fdd0859ea89e2749e462058102e3af11980644586ef18cac0ceae6ffe484b5103c4877fe8e7b0383a8bc4d73c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
